version: "3.9"
services:
  bot:
    build: .
    environment:
      - DISCORD_TOKEN
      - DISCORD_GUILD_LIST
      - REDIS_HOST=redis://cache:6379
    depends_on:
      - redis
    restart: unless-stopped
  cache:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - cache:/data
    restart: unless-stopped
volumes:
  cache:
