version: "3.9"
services:
  bot:
    build: .
    environment:
      - BOT_TOKEN
      - CMD_MODE
      - CMD_SYNC_GUILDS
      - REDIS_HOST=redis://cache:6379
    depends_on:
      - cache
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
  cache:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - cache:/data
    restart: unless-stopped
volumes:
  cache:
